### ISSUE TITLE
Fibers at edge of petal 1 rejected on 2025-07-28

### ISSUE THREAD

**Issue by djschlegel** [desihub/desisurveyops#333]
During the night of 2025-07-28, a group of a few dozen fibers at the edge of petal 1 are rejected on many, but not all, of the tiles.  Those fibers have good positioning.  The following 8 tiles have been marked as unsure in QA: 10680, 5730, 1873, 100495, 100492, 100489, 102575, 100168.  Further investigation shows that the BADFLAT bit has been set in the ZWARN flag for those fibers.  That bit should only be set for fibers where 25% of the pixels have MASK > 0 or IVAR < 1e-8, but the extracted spectra don't show such problems.  As an example, see the file spectra-1-10680-thru20250728.fits.gz for tile 10680.

Below is the QA plot for tile 10680.

<img width="537" height="526" alt="Image" src="https://github.com/user-attachments/assets/bd2d873b-cf40-4128-b1a5-fbdaf2948ca0" />

**Comment by forero** [comment]
We've spotted similar patterns at the edge of petal 1 in the past: see #282 and #313. Somehow it was fixed after reprocessing. I don't recall what exactly changed in reprocessing, though.

**Comment by djschlegel** [comment]
Julien Guy points out that I was incorrectly interpreting the mask bits.  Bit 18 in ZWARN is BAD_SPECQA (https://desidatamodel.readthedocs.io/en/latest/bitmasks.html#zwarn-bitmask ).  SPEC1 has a lower flat-field on the edge of the petal and higher read noise on amps A+C that conspire to make those edge fibers drop below our S/N threshold.  This still doesn't explain how the reprocessing of some tiles in issue #282 "recovered" those edge fibers of petal 1.
