### ISSUE TITLE
Pileup of redshifts at z=1 on exp 154157(8) in tile 7438

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisurveyops#76]
This split exposure has what appears to be a large number of redshifts just below z=1. It could be a normal fluctuation but I marked it as unsure just to be cautious.
![Screen Shot 2022-11-30 at 9 24 23 AM](https://user-images.githubusercontent.com/7385438/204821226-8156c443-4c39-488f-aec2-e4ada357f6be.png)

**Comment by schlafly** [comment]
Anand has investigated the "redshift 0.9" bug here:
https://desisurvey.slack.com/archives/C01HNN87Y7J/p1669832258548009
They are all stuck fibers with flux == ivar == 0.

We have two outstanding items here:
1. I think we need to update QA to not show redshifts with flux == ivar == 0 for all wavelength elements.  Those aren't useful redshifts and having them cut through the middle of the real redshift distribution makes it hard to see what's actually going on at that redshift.  But we also probably need a box somewhere saying (number of redshifts with flux == ivar == 0: XYZ).
2. Anand diagnosed that the flux == ivar == 0 redshifts started some time between May 2021 and Feb 2022.  It's weird to have 200 stuck fibers that have flux == ivar == 0; that smells like a bug?

That said, I'm leaving this tile as unsure because fo the P9 unstable amplifier feature.

**Comment by julienguy** [comment]
flux == ivar == 0 set by the pipeline is probably more a feature than a bug. it's a decision that was made to set to 0 fiber spectra with bad FIBERSTATUS in the calibrated frames. We may revise this.

**Comment by julienguy** [comment]
- I am looking at cframe files of exposure 20221121/00154157 and I don't see any fiber with flux set to 0 (for the cameras I looked at).
- I see it in the coadds thought. And for those it makes sense: we don't want to include in the coadds spectra with fibers that where not well positioned!
- So it's natural that in the coadds, the spectra of stuck positioners have flux=0 ivar=0. 
- I am not sure there any action to take here (except understanding why there is a bizarre default redshift).

**Comment by araichoor** [comment]
thanks for the follow-up.
I must have looked at the coadds, indeed.
remark : looking at the cframes, those unassigned stuck fibers have `IVAR=0`, still; but maybe that s ok, don t know..

**Comment by julienguy** [comment]
No it's not ok. How do I get the 'unassigned stuck fibers'?

**Comment by julienguy** [comment]
Ok thanks. I confirm the fibers we can select them from the fibermap["FIBERSTATUS"] as 
`(STUCKPOSITIONER and UNASSIGNED ) or BROKENFIBER ` have `ivar=0` in the `sframe` and `cframe` files. We do not want that for `STUCKPOSITIONER and UNASSIGNED` because that prevents us from studying those fiber spectra (for instance to extend the list of sky fibers).

**Comment by schlafly** [comment]
Just for posterity, this issue has two components:
1. stuck fibers not assigned to sky getting zeroed out
2. 7438 having unstable amplifiers and needing to be marked bad.
The latter is now addressed as part of https://github.com/desihub/desisurveyops/issues/79.

**Comment by akremin** [comment]
desispec PR 1942 (https://github.com/desihub/desispec/pull/1942) removes the cut on `UNASSIGNED` fibers such that they no longer have ivar=0. This is true for everything including the coadds. Iif we want them to be ivar=0 in the coadds, we will need to add that back in.

As Julien mentions in the PR, this doesn't solve why the ivar=0 redshifts are non-zero in the new perlmutter code but it does reduce the number of ivar=0 spectra that fall into that bucket.
